baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Mike Schweitzer'

[module]
  [[module.imports]]
    path = "gitlab.com/kaushalmodi/hugo-mwe-theme"
    path = "github.com/panr/hugo-theme-hello-friend"